<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.dsc</groupId>
  <artifactId>managed-python-nifi-parent</artifactId>
  <version>3.3.0</version>
  <packaging>pom</packaging>

  <properties>
    <maven.compiler.release>21</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <nifi.version>2.10.0</nifi.version>
    <grpc.version>1.66.0</grpc.version>
    <protobuf.version>4.28.2</protobuf.version>
  </properties>

  <modules>
    <module>managed-python-processors</module>
    <module>managed-python-nar</module>
  </modules>

  <build>
    <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>  <!-- 3.6+ 才支持 release 参数 -->
                <configuration>
                    <release>${maven.compiler.release}</release>
                </configuration>
            </plugin>
        </plugins>
    </pluginManagement>
</build>
</project>
